# Generated by Django 2.2.3 on 2020-02-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20191008_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizno',
            field=models.CharField(default='defaul', max_length=255),
            preserve_default=False,
        ),
    ]
