# Generated by Django 2.2.7 on 2020-02-23 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200223_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
