# Generated by Django 2.2.7 on 2020-02-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_quiz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
