# Generated by Django 2.2.7 on 2020-02-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200223_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='empty', upload_to='images/'),
            preserve_default=False,
        ),
    ]
