# Generated by Django 2.2.7 on 2020-02-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
